export const Errors = {
    UNKNOWN: 'UNKNOWN',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_SIZE: 'INVALID_SIZE',
    INVALID_ID: 'INVALID_ID',
    EMPTY_NAME: 'EMPTY_NAME',
    SMALL_NAME: 'SMALL_NAME',
    BIG_NAME: 'BIG_NAME',
    NAME_WITHOUT_LAST_NAME: 'NAME_WITHOUT_LAST_NAME',
    NAME_WITH_INVALID_CHARACTERS: 'NAME_WITH_INVALID_CHARACTERS'
} as const